### ISSUE TITLE
Question about luancher.m

### ISSUE THREAD

**Issue by yc67** [shuochsu/DeepVideoDeblurring#1]
Hi! I'm trying to align some of my own testing images, and when I ran the launcher.m, I'm receiving the following error: 
Attempt to execute SCRIPT tvl1flow as a function:
...\DeepVideoDeblurring-master\preprocess\thirdparty\tvl1flow_3_mex\tvl1flow.m

Error in genFlow (line 16)
flo_i0 = tvl1flow(v0g, vig, DWNSMP, TAU, LAMBDA, THETA,...

Error in launcher (line 78)
                        flo_i0 = genFlow(v0g, vig);

==
I'm running the code in matlab when I met this problem. Do I need to setup something else to run it correctly?

Thanks,
Jun.

**Comment by shuochsu** [comment]
Hi! You are supposed to compile the mex file by executing preprocess/thirdparty/tvl1flow_3_mex/compile_mex.m in MATLAB.

**Comment by Deephome** [comment]
Hello, @shuochsu 
 I run compile_mex.m, but got following errors, can you give me some suggestions?
e:\code\matlab\去模糊_开源\deepvideodeblurring-master\preprocess\thirdparty\tvl1flow_3_mex\mask.c(238) : error C2057: 应输入常量表达式
e:\code\matlab\去模糊_开源\deepvideodeblurring-master\preprocess\thirdparty\tvl1flow_3_mex\mask.c(238) : error C2466: 不能分配常量大小为 0 的数组
e:\code\matlab\去模糊_开源\deepvideodeblurring-master\preprocess\thirdparty\tvl1flow_3_mex\mask.c(238) : error C2133: “B”: 未知的大小
