### ISSUE TITLE
Can I ask you how split the dataset into 61 training videos and 10 testing videos?

### ISSUE THREAD

**Issue by stephenjia** [shuochsu/DeepVideoDeblurring#2]
Hi Shuochen,

Can I ask you how split the dataset into 61 training videos and 10 test videos?

Thanks a lot!

**Comment by shuochsu** [comment]
Here are the folder names of the test sets:

#1: IMG_0030
#2: IMG_0049
#3: IMG_0021
#4: 720p_240fps_2
#5: IMG_0032
#6: IMG_0033
#7: IMG_0031
#8: IMG_0003
#9: IMG_0039
#10: IMG_0037

We only used 30 frames from each test set for calculating the PNSR/MSSIM scores in Table 2. The frame indices can be generated in MATLAB as follows:

fr_idx = floor(linspace(2,97,30));

**Comment by stephenjia** [comment]
Thanks a lot for your explanation!

**Comment by ezjong** [comment]
Hello Shuochen,
a follow up question on this: The frame indices generated by the Matlab code above are counting from 1, right?

Thanks!

**Comment by gauenk** [comment]
Here are two text files of the train/test split for future reference.

[train.txt](https://github.com/shuochsu/DeepVideoDeblurring/files/12361256/train.txt)
[test.txt](https://github.com/shuochsu/DeepVideoDeblurring/files/12361257/test.txt)

**Comment by ToaToaDigital** [comment]
How can I deblur a video from file using VSCODE?
