### ISSUE TITLE
 How can I get the same results in your paper?

### ISSUE THREAD

**Issue by Git-H2K** [shuochsu/DeepVideoDeblurring#3]
Hi! I compiled your code and computed PSNR using MATLAB function.
However, I got silightly different results.
                        #1	#2	#3	#4	#5	#6	#7	#8	#9	#10	avg
(Noallign-paper)	27.83	33.11	31.29	29.73	25.12	32.52	30.8	27.28	33.32	29.51	30.05
(Noallign-test )	28.28	32.51	31.08	30.07	24.91	31.87	30.11	26.84	33.59	29.21	29.85

setting : 

OS : ubuntu 16.04
VGA : titan X
preprocess : alignment = '_nowarp'
run_pred.sh 
params
ALIGNMENT="_nowarp"
MODEL="model2_symskip_nngraph2_deeper"
METHOD=""
REALSET="data/testing_real_all_nostab"$ALIGNMENT
FN="1108_"$MODEL$ALIGNMENT$METHOD
FNREAL=$FN"_real"
GPUID=0
EPOCHTEST=400

How can I get the same results in your paper ?

Thanks!
HH.

**Comment by shuochsu** [comment]
Hi Hyun-Ho, we used the evaluation code of Koehler et al. to calculate the PSNRs, which aligns the image pairs first. Their implementation of the metric is also slightly different compared to the naive MATLAB function. You may check it out here,
http://people.kyb.tuebingen.mpg.de/rolfk/BenchmarkECCV2012/evaluation_code.zip

**Comment by Git-H2K** [comment]
Thanks :)
