### ISSUE TITLE
Got errors

### ISSUE THREAD

**Issue by Harry-675** [shuochsu/DeepVideoDeblurring#6]
=> loading parameters
/home/harry/torch/install/bin/luajit: cannot open <logs/1024_model2_symskip_nngraph2_deeper_OF/param_epoch_400.t7> in mode r  at /tmp/luarocks_torch-scm-1-8876/torch7/lib/TH/THDiskFile.c:673
stack traceback:
        [C]: at 0x7fe8a8a2e470
        [C]: in function 'DiskFile'
        /home/harry/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
        inference.lua:41: in function 'load_model'
        inference.lua:86: in main chunk
        [C]: in function 'dofile'
        ...arry/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
{
  max_intensity : 255
  seed : 123
  patch_size : 256
  patchbypatch : 1
  gpuid : 0
  n : 100
  num_frames : 5
  num_channels : 3
  model_param : "logs/1024_model2_symskip_nngraph2_deeper_OF/param_epoch_400.t7"
  model : "model2_symskip_nngraph2_deeper"
  saveDir : "outImg/1024_model2_symskip_nngraph2_deeper_OF_real/sup"
  bn_meanstd : "logs/1024_model2_symskip_nngraph2_deeper_OF/bn_meanvar_epoch_400.t7"
  data_root : "data/testing_real_all_nostab_OF/sup"
  start_id : 1
}
==> configuring model
number of parameters: 15305291
==> loading parameters
/home/harry/torch/install/bin/luajit: cannot open <logs/1024_model2_symskip_nngraph2_deeper_OF/param_epoch_400.t7> in mode r  at /tmp/luarocks_torch-scm-1-8876/torch7/lib/TH/THDiskFile.c:673
stack traceback:
        [C]: at 0x7f0873cf9470
        [C]: in function 'DiskFile'
        /home/harry/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
        inference.lua:41: in function 'load_model'
        inference.lua:86: in main chunk
        [C]: in function 'dofile'
        ...arry/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
{
Please help me!

**Comment by shuochsu** [comment]
Hi there,

Did you follow the instruction and download the pretrained model first? Here is the link:
http://www.cs.ubc.ca/labs/imager/tr/2017/DeepVideoDeblurring/pretrained.zip

Thanks,
Shuochen
